@url = http://localhost:8080/api/categories
POST {{url}}
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MjkwMjM0ODgsImV4cCI6MTYyOTAzMDY4OCwidXNlcklkIjoyLCJlbWFpbCI6Imp0MkBnbWFpbC5jb20iLCJmaXJzdE5hbWUiOiJKYXNvbjIiLCJsYXN0TmFtZSI6IlRhbmcyIn0.-OTFPRlX4SxDOxr6QjQ_BndKtvJhzfjcBev_K8oDPhg

{
    "title": "Shopping",
    "description": "shopping transactions"
}